# PHP-Movic - base platform for PHP applications.
# Copyright (C) 2024 Jiri Skoda <developer@skodaj.cz>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# 

#
# This file contains configuration of whole PHP-Movic installation.
# Documentation for whole PHP-Movic base platform can be found
# at https://github.com/byte98/PHP-Movic. There is also Wiki pages
# describing this configuration file at
# https://github.com/byte98/PHP-Movic/wiki/Configuration
#

# Default format of date used in application.
# See https://github.com/byte98/PHP-Movic/wiki/Date-format
DateFormat: "%0d%-%0m%-%y% %0H%:%0M%:%0S%.%0U%"


# Flag, whether PHP errors should be displayed or not.
# Allowed values:
#   True: display PHP errors
#   False: do not display PHP errors
PHPErrors: True

# Flag, whether application should make logs.
# Allowed values:
#   True: make logs
#   False: do not make logs
LogsAllowed: True

# Minimal level of log whihc will be actually outputted.
# Allowed values: LOW, BASE, INFO, SUCCESS, WARNING, ERROR, CRITICAL
LogLevel: LOW

# Directory where all log files will be stored.
LogDir: "LOGS"

# Flag, whether logs will be printed also to standard output.
# Allowed values: True, False
LogStdout: True

# Format of logs.
# See https://github.com/byte98/PHP-Movic/wiki/Log-format
LogFormat: "%DATE% [ %LEVEL ]: %MESSAGE%"

# Flag, whether format symbols will be used when logging into file.
# Allowed values: True, False
LogUseFormat: False

# Specifies format of log by level.
# Syntax:
# LogLevelFormat:
#    <level>: "<format">
#    <level>: "<format>"
#    ...
# where <level> is one of: LOW, BASE, INFO, SUCCESS, WARNING, ERROR, CRITICAL
# and <format> is format string of log (same as LogFormat)
# This setting overrides LogFormat.
LogLevelFormat:
    LOW: "%I%%CF[GRAY]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    BASE: "%CF[WHITE]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    INFO: "%CF[CYAN]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    SUCCESS: "%CF[GREEN]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    WARNING: "%CF[YELLOW]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    ERROR: "%CF[RED]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"
    CRITICAL: "%B%%CF[WHITE]%%CB[RED]%%DATE% [ %LEVEL ]: %MESSAGE%%FR%"

# Name or address of the database server.
DatabaseHost: "localhost"

# Name of database to which application will connect to.
DatabaseName: "php_movic"

# Name of user with access to database.
DatabaseUser: "username"

# Password of user with access to database.
DatabasePassword: "password"
