# PHP-Movic - base platform for PHP applications.
# Copyright (C) 2024 Jiri Skoda <developer@skodaj.cz>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# 

#
# This file contains configuration of whole PHP-Movic installation.
# Documentation for whole PHP-Movic base platform can be found
# at https://github.com/byte98/PHP-Movic. There is also Wiki pages
# describing this configuration file at
# https://github.com/byte98/PHP-Movic/wiki/Configuration
#

# Default format of date used in application.
# See https://github.com/byte98/PHP-Movic/wiki/Date-format
DateFormat: "%0d%-%0m%-%y% %0H%:%0M%:%0S%.%0U%"

# Default time zone for whole application.
# For more information, please see https://www.php.net/manual/en/timezones.php.
Timezone: "Europe/Prague"

# Flag, whether PHP errors should be displayed or not.
# Allowed values:
#   True: display PHP errors
#   False: do not display PHP errors
PHPErrors: True

# File to which counters will be stored.
# PHP-Movic uses various counters across whole application. To store
# them in one place, all counters will be stored in one file.
Counters: "COUNTERS.TXT"

# Namespace of all user content. All classes in /CONTENT folder
# are expected to be in this namespace.
# Example: assuming ContentNamespace is "MyApp"
#          class "MyApp\Controller\SuperController" is expected to
#          be in file "/CONTENT/CONTROLLER/SUPERCONTROLLER.PHP"
# Note: this setting (with pathing mentioned in example above) is
# case insensitive. So, namespace "MyApp" is the same as "MYAPP".
ContentNamespace: "MyApp"

# Flag, whether application should make logs.
# Allowed values:
#   True: make logs
#   False: do not make logs
LogsAllowed: True

# Minimal level of log whihc will be actually outputted.
# Allowed values: DEBUG, LOW, BASE, INFO, SUCCESS, WARNING, ERROR, CRITICAL
LogLevel: DEBUG

# Directory where all log files will be stored.
LogDir: "LOGS"

# Flag, whether logs will be printed also to standard output.
# Allowed values: True, False
LogStdout: True

# Format of logs.
# See https://github.com/byte98/PHP-Movic/wiki/Log-format
LogFormat: "%DATE% [ %PDLVL% ]: %MESSAGE%"

# Flag, whether format symbols will be used when logging into file.
# Allowed values: True, False
LogUseFormat: False

# Specifies format of log by level.
# Syntax:
# LogLevelFormat:
#    <level>: "<format">
#    <level>: "<format>"
#    ...
# where <level> is one of: DEBUG, LOW, BASE, INFO, SUCCESS, WARNING, ERROR, CRITICAL
# and <format> is format string of log (same as LogFormat)
# This setting overrides LogFormat.
LogLevelFormat:
    DEBUG: "%I%%CF[GRAY]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    LOW: "%CF[GRAY]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    BASE: "%CF[WHITE]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    INFO: "%CF[CYAN]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    SUCCESS: "%CF[GREEN]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    WARNING: "%CF[YELLOW]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    ERROR: "%CF[RED]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"
    CRITICAL: "%B%%CF[WHITE]%%CB[RED]%%DATE% [ %PDLVL% ]: %MESSAGE%%FR%"

# Flag, whether logs should be also printed
# to browser console.
# Allowed values: True, False
#
# Note: this setting is also affected by LogUseFormat.
LogConsole: True

# Name or address of the database server.
DatabaseHost: "localhost"

# Name of database to which application will connect to.
DatabaseName: "php_movic"

# Name of user with access to database.
DatabaseUser: "username"

# Password of user with access to database.
DatabasePassword: "password"

# Definition of routes of application.
# Syntax:
# Routes:
#    "<route>": "<controller>"
#    "<route>": "<controller>"
#    "<route>": "<controller>"
#    ...
# Where <route> is any path and <controller> is name of class.
# For more, please see 
# https://github.com/byte98/PHP-Movic/wiki/Configuration#routes
Routes:
    "/": "HomePageController"
    "/id/%ID::INTEGER%": "IdController"

# Definitions of routes to static content.
# Syntax:
# StaticRoutes:
#    "<route>": "<path>"
#    "<route>": "<path>"
#    ...
# Where <route> is any path of request and <path> is path
# to folder within /CONTENT folder.
StaticRoutes:
    "/static/css": "/STATIC/STYLES"
    "/static/js": "/STATIC/SCRIPTS"
